[tool.black]
line-length = 100

[tool.isort]
line_length = 100
profile = "black"
skip_glob = "*/migrations/*.py"
skip = "virtualenv, .tox"

[tool.mypy]
allow_untyped_globals = true
follow_imports = "silent"
ignore_missing_imports = true

[tool.autoflake]
in_place = true
recursive = true
imports = ["django", "requests", "urllib3"]
exclude = ["node_modules", "venv", "virtualenv"]
remove_all_unused_imports = true
ignore_init_module_imports = true
ignore_pass_after_docstring = true
